### ISSUE TITLE
Embedded JAR won't start

### ISSUE THREAD

**Issue by gchauvet** [poidasmith/winrun4j#45]
Hello,

I obtain a NoClassDefFoundError "IllegalName" with Winrun4j 0.4.5.
Please find below, the whole draft configuration.

Regards,
Guillaume
# TEST.ini:

working.directory=.
main.class=com.Test
vm.heapsize.preferred=512
single.instance=process
process.priority=above_normal
vmarg.1=-XX:+UseConcMarkSweepGC
vmarg.2=-XX:+CMSClassUnloadingEnabled
vmarg.3=-XX:+CMSPermGenSweepingEnabled
vm.version.min=1.6.0_43
vm.version.max=1.6.0_45
# Linkage:

RCEDIT64.exe /C TEST64.exe
RCEDIT64.exe /N TEST64.exe TEST.ini
RCEDIT64.exe /I TEST64.exe TEST.ico
RCEDIT64.exe /J TEST64.exe test.jar
- The test.jar contains a main class: com/Test.class
# Output:

C:\Program Files\Test>TEST64.exe
C:\Program Files\Test>[info] Module Name: C:\Program Files\Test\TEST64.exe
[info] Module INI: C:\Program Files\Test\TEST64.ini
[info] Module Dir: C:\Program Files\Test\
[info] INI Dir: C:\Program Files\Test\
[info] Working directory set to: C:\Program Files\Test
[info] Configured vm.location: (null)
[info] Found VM: C:\Program Files\Java\jre6\bin\server\jvm.dll
[info] Generated Classpath:
[info] VM Args:
[info] vmarg.0=-XX:+UseConcMarkSweepGC
[info] vmarg.1=-XX:+CMSClassUnloadingEnabled
[info] vmarg.2=-XX:+CMSPermGenSweepingEnabled
[info] vmarg.3=-Djava.class.path=
[info] vmarg.4=-Xmx512m
[info] Registering natives for Native class
[warn] Could not find Native class
 [err] Could not find or initialize main class
java.lang.NoClassDefFoundError: IllegalName: com/Test
        at java.lang.ClassLoader.preDefineClass(Unknown Source)
        at java.lang.ClassLoader.defineClassCond(Unknown Source)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at org.boris.winrun4j.classloader.EmbeddedClassLoader.findClass(Embedded
ClassLoader.java:98)

**Comment by bdw429s** [comment]
@poidasmith What became of this ticket?  Was there a fix?  Is something preventing us from incorporating the fix from @NathanSweet ?  I am hitting this same issue and disheartened to see a 6 year old thread with no apparent resolution.

**Comment by matthieu-labas** [comment]
WinRun4J is not maintained anymore. JSmooth also (the installer is crashing on my Windows 10). Unfortunately it seems it's the only one able to "replace" the java.exe name with the one specified so we'll juste have to live with it (unless able to recompile it, which looks like a mess...).
